apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T12:51:46Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "6531"
  uid: e3fa9e60-2f78-4326-9633-d0b23b9ce72f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.148.137
  clusterIPs:
  - 10.99.148.137
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30749
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}